# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adopt a code
email: info@adoptacode.net
description: > # this means to ignore newlines until "baseurl:"
  Adoptacode is a Free Software conservancy project. It put in relation developers
  with projects without maintainers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adoptacode.net" # the base hostname & protocol for your site
twitter_username: adoptacode
github_username:  adoptacode

# Build settings
markdown: kramdown
